### ISSUE TITLE
Config just sucks

### ISSUE THREAD

**Issue by MrBlasyMSK** [alvin0319/GroupsAPI#14]
I have created all the ranges including the permissions from the configuration and the plugin is simply ignoring it, no matter how well I have set it when using /groups in the groups, none of the permissions I have added to the groups appear

Example:
```yml
  Ayudante:
    priority: 4
    permissions:
      - pocketmine.command.teleport
      - weather.command
      - pocketmine.command.time.set
      - pocketmine.command.teleport.self
      - pocketmine.command.teleport.other
```
![unknown (2)](https://user-images.githubusercontent.com/85447029/162629051-d4b08e3f-8cd7-48f2-ad1c-cd6a674345d1.png)

**Comment by alvin0319** [comment]
Can you send full config so that I can look into it?

**Comment by MrBlasyMSK** [comment]
I don't think the chat is revealing, so I won't add it.
The only way to add permissions and have them work properly is to edit the group from the game (but it has a length limit and won't let you add more).
```yml
# GroupsAPI Main configuration file
# Configurations in this file may not appear automatically upon update, and some settings may crash the server.
database:
  # The database type. "sqlite" and "mysql" are supported.
  type: sqlite

  # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
    # You can also put an absolute path here.
    file: data.sqlite
  # Edit these settings only if you choose "mysql".
  mysql:
    host: 127.0.0.1
    # Avoid using the "root" user for security reasons.
    username: root
    password: ""
    schema: your_schema
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 1

remove-op-and-deop:
  # Whether to remove op and deop command from the PocketMine.
  # Recommend setting this to true to prevent any unwanted op/deop from being executed.
  enabled: true

default-groups:
  # Default groups to be added on database
  # Formats should be like:
  # NameOfGroup:
  #   priority: priority_declared_in_priorities
  #   permissions:
  #     - somepermission
  #     - somepermission2
  #
  # If you want to use different priority register priority at priorities
  Creador:
    priority: 0
    permissions:
      - pocketmine.group.operator
      - per-world-player.bypass
  Admin:
    priority: 1
    permissions:
      - pocketmine.group.operator
      - per-world-player.bypass
  Constructor:
    priority: 2
    permissions:
      - pocketmine.command.gamemode
      - pocketmine.command.effect
      - buildertools.command
      - limitcreative.bypass
  Moderador:
    priority: 3
    permissions:
      - pocketmine.command.gamemode
      - pocketmine.command.clear.self
      - pocketmine.command.kick
      - pocketmine.command.ban.ip
      - pocketmine.command.ban.list
      - pocketmine.command.ban.player
      - pocketmine.command.teleport
      - pocketmine.command.unban.ip
      - pocketmine.command.unban.player
  Ayudante:
    priority: 4
    permissions: []
  Maestro:
    priority: 5
    permissions: []
  Diamante:
    priority: 6
    permissions: []
  Platino:
    priority: 7
    permissions: []
  Oro:
    priority: 8
    permissions: []
  Plata:
    priority: 9
    permissions: []
  Miembro:
    priority: 10
    permissions: 
    - pocketmine.command.clear.self
    - pocketmine.command.help
    - pocketmine.command.kill.self
    - pocketmine.command.me
    - pocketmine.command.tell

priorities:
  # Default priorities to be used on sort groups
  # Lower means When sorted, they are sorted in the highest order

  0: Creador
  1: Admin
  2: Constructor
  3: Moderador
  4: Ayudante
  5: Maestro
  6: Diamante
  7: Platino
  8: Oro
  9: Plata
  10: Miembro

# The default groups that will be added to new players
# You can add multiple groups
default-groups-player:
  - Miembro
  ```
  
  In game perms:
[Server thread/INFO]: [GroupsAPI] Showing all groups...
[Server thread/INFO]: Creador (priority: 0, permissions: pocketmine.group.operator, per-world-player.bypass)
[Server thread/INFO]: Admin (priority: 1, permissions: pocketmine.group.operator)
[Server thread/INFO]: Constructor (priority: 2, permissions: )
[Server thread/INFO]: Moderador (priority: 3, permissions: )
[Server thread/INFO]: Ayudante (priority: 4, permissions: pocketmine.command.teleport,  weather.command,  pocketmine.command.time.set)
[Server thread/INFO]: Maestro (priority: 5, permissions: )
[Server thread/INFO]: Diamante (priority: 6, permissions: )
[Server thread/INFO]: Platino (priority: 7, permissions: )
[Server thread/INFO]: Oro (priority: 8, permissions: )
[Server thread/INFO]: Plata (priority: 9, permissions: )
[Server thread/INFO]: Miembro (priority: 10, permissions: )

@alvin0319
